### ISSUE TITLE
Evaluate kubernetes distributions for local deployment

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#6]
several distributions for local kubernetes deployments exists, eg k3s, microk8s 
Task is to check which one is most suitable. Current expectation is that k3s fits best

epic #1

**Comment by max-grzanna** [comment]
As already suspected, K3s seems to be the most fitting distribution. Especially because of the low resource consumption. Some notes on the decision-making process can be found here: [Wiki notes](https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/wiki/Evaluation-of-the-distributions)
